import frappe
from frappe import _
from frappe.utils import flt, now_datetime
from frappe_wms.services.stock import transfer_stock, release_allocation
from frappe_wms.services.determination import determine_destination_bin
from frappe_wms.services.bin_rules import validate_destination_bin
from frappe_wms.services.warehouse_order import attach_task, sync_warehouse_order, release_next_in_sequence
from frappe_wms.services.printing import create_print_spool
from frappe_wms.utils import require_role

TASK_TYPE_BY_REQUEST = {
    "Unload": "Unload", "Putaway": "Putaway", "Pick": "Pick", "Replenish": "Putaway",
    "Internal Move": "Internal Move", "Stage": "Stage", "Load": "Load",
    "Unload Vehicle": "Unload", "Posting Change": "Posting Change", "Inventory Count": "Inventory Count",
}

def create_tasks_for_request(request_name, batch_key=None):
    frappe.db.sql("select name from `tabWarehouse Request` where name=%s for update", request_name)
    request = frappe.get_doc("Warehouse Request", request_name)
    if request.status not in {"Draft", "Open", "Partially Tasked"}: frappe.throw(_("Warehouse Request is not open for tasking"))
    remaining = flt(request.requested_quantity) - flt(request.created_quantity)
    if remaining <= 0: frappe.throw(_("Warehouse Request is already fully tasked"))
    task_type = TASK_TYPE_BY_REQUEST.get(request.request_type)
    if not task_type: frappe.throw(_("No warehouse task type mapped for request type {0}").format(request.request_type))
    process_type = frappe.get_cached_doc("Warehouse Process Type", request.process_type) if request.process_type else None
    movement_type = process_type.movement_type if process_type else None
    if not movement_type: frappe.throw(_("Warehouse Process Type must define a movement type before tasking"))
    destination_bin = request.destination_bin
    if not destination_bin and process_type and process_type.destination_required:
        hu_type = frappe.db.get_value("Handling Unit", request.source_hu, "hu_type") if request.source_hu else None
        source_storage_type = frappe.db.get_value("Storage Bin", request.source_bin, "storage_type") if request.source_bin else None
        gross_weight_per_unit = frappe.db.get_value("WMS Product", request.product, "gross_weight_per_unit")
        incoming_weight = flt(gross_weight_per_unit) * remaining if gross_weight_per_unit else None
        destination_bin = determine_destination_bin({"warehouse": request.warehouse, "activity": process_type.activity, "item": request.product, "stock_type": request.stock_type, "hu_type": hu_type, "source_storage_type": source_storage_type, "incoming_weight": incoming_weight, "destination_hu": request.destination_hu or request.source_hu})
    task = frappe.get_doc({"doctype": "Warehouse Task", "warehouse_request": request.name, "task_type": task_type, "warehouse": request.warehouse, "product": request.product, "planned_quantity": remaining, "stock_uom": request.stock_uom, "source_bin": request.source_bin, "destination_bin": destination_bin, "source_hu": request.source_hu, "destination_hu": request.destination_hu, "stock_type_from": request.stock_type, "stock_type_to": request.stock_type, "movement_type": movement_type, "priority": request.priority or "Normal", "status": "Open", "idempotency_key": f"WT:{request.name}"})
    attach_task(task, batch_key or frappe.generate_hash(length=10), reference_doctype="Warehouse Request", reference_name=request.name)
    task.insert(ignore_permissions=True)
    frappe.db.set_value("Warehouse Request", request.name, {"created_quantity": flt(request.created_quantity) + remaining, "status": "Fully Tasked"})
    return task.name

def create_and_confirm_move(*, warehouse, product, quantity, stock_uom, stock_type, source_bin=None, source_hu=None, destination_bin, destination_hu=None, batch_no=None, serial_no=None, device=None):
    # The ad-hoc "move this HU/bin's stock to that bin now" action an RF operator does
    # directly from the floor (SAP EWM's immediate/direct TO creation), as opposed to a
    # planned task generated by putaway/picking/replenishment. Creates and confirms the
    # Warehouse Task as one action since there is no separate planning step to wait on.
    require_role("WMS Operator", "WMS Supervisor")
    hu_type = frappe.db.get_value("Handling Unit", source_hu, "hu_type") if source_hu else None
    gross_weight_per_unit = frappe.db.get_value("WMS Product", product, "gross_weight_per_unit")
    incoming_weight = flt(gross_weight_per_unit) * flt(quantity) if gross_weight_per_unit else None
    validate_destination_bin(destination_bin, item=product, stock_type=stock_type, hu_type=hu_type,
        batch_no=batch_no, destination_hu=destination_hu or source_hu, incoming_weight=incoming_weight)
    process_type = frappe.get_cached_doc("Warehouse Process Type", "INTERNAL_MOVE")
    task = frappe.get_doc({
        "doctype": "Warehouse Task", "task_type": "Internal Move", "warehouse": warehouse, "product": product,
        "planned_quantity": quantity, "stock_uom": stock_uom, "batch_no": batch_no, "serial_no": serial_no,
        "source_bin": source_bin, "destination_bin": destination_bin, "source_hu": source_hu, "destination_hu": destination_hu,
        "stock_type_from": stock_type, "stock_type_to": stock_type, "movement_type": process_type.movement_type,
        "priority": "Normal", "status": "Open",
    })
    task.insert(ignore_permissions=True)
    return confirm_task(task.name, confirmed_quantity=quantity, device=device)

def create_pick_tasks(delivery_name, strategy="Single Order"):
    require_role("WMS Operator", "WMS Picker", "WMS Supervisor")
    delivery = frappe.get_doc("Outbound Delivery", delivery_name)
    if delivery.docstatus != 1: frappe.throw(_("Outbound Delivery must be submitted before picking tasks can be created"))
    if not delivery.staging_bin: frappe.throw(_("Outbound Delivery must have a staging bin before picking tasks can be created"))
    allocations = frappe.get_all("Stock Allocation", filters={"outbound_delivery": delivery_name, "status": "Allocated"}, fields=["*"])
    if not allocations: frappe.throw(_("No open allocations to create pick tasks for"))
    created = _create_pick_tasks_from_allocations(allocations, strategy)
    delivery.db_set("status", "Picking")
    return created

def create_pick_tasks_for_wave(delivery_names, strategy="Single Order", wave=None):
    require_role("WMS Operator", "WMS Picker", "WMS Supervisor")
    for delivery_name in delivery_names:
        docstatus, staging_bin = frappe.db.get_value("Outbound Delivery", delivery_name, ["docstatus", "staging_bin"])
        if docstatus != 1: frappe.throw(_("Outbound Delivery {0} must be submitted before picking tasks can be created").format(delivery_name))
        if not staging_bin:
            frappe.throw(_("Outbound Delivery {0} must have a staging bin before picking tasks can be created").format(delivery_name))
    allocations = frappe.get_all("Stock Allocation", filters={"outbound_delivery": ["in", delivery_names], "status": "Allocated"}, fields=["*"])
    if not allocations: frappe.throw(_("No open allocations to create pick tasks for"))
    created = _create_pick_tasks_from_allocations(allocations, strategy, wave=wave)
    for delivery_name in delivery_names:
        frappe.db.set_value("Outbound Delivery", delivery_name, "status", "Picking")
    return created

def _create_pick_tasks_from_allocations(allocations, strategy, wave=None):
    process_type = frappe.get_cached_doc("Warehouse Process Type", "OB_PICK")
    deliveries = {}
    for allocation in allocations:
        if allocation.outbound_delivery not in deliveries:
            deliveries[allocation.outbound_delivery] = frappe.db.get_value(
                "Outbound Delivery", allocation.outbound_delivery, ["warehouse", "staging_bin", "priority"], as_dict=True,
            )
        delivery = deliveries[allocation.outbound_delivery]
        allocation["_warehouse"] = delivery.warehouse
        allocation["_staging_bin"] = delivery.staging_bin
        allocation["_priority"] = delivery.priority

    if strategy == "Cluster":
        groups = {}
        for allocation in allocations:
            key = (allocation._warehouse, allocation.storage_bin, allocation.handling_unit, allocation.product,
                allocation.batch_no, allocation.serial_no, allocation.stock_type, allocation._staging_bin)
            groups.setdefault(key, []).append(allocation)
        groups = list(groups.values())
    else:
        groups = [[allocation] for allocation in allocations]

    batch_key = frappe.generate_hash(length=10)
    created = []
    for group in groups:
        created.append(_create_pick_task_for_group(group, process_type, wave, batch_key))
    for allocation in allocations:
        frappe.db.set_value("Stock Allocation", allocation.name, "status", "Released")
    return created

def _create_pick_task_for_group(allocations, process_type, wave, batch_key):
    first = allocations[0]
    stock_uom = frappe.db.get_value("WMS Stock Balance", first.stock_balance, "stock_uom")
    total_qty = sum(flt(a.allocated_quantity) for a in allocations)
    sequence = frappe.db.get_value("Storage Bin", first.storage_bin, "sequence") or 0
    priority_order = ("Low", "Normal", "High", "Urgent")
    priority = max((a._priority or "Normal" for a in allocations), key=priority_order.index)
    task = frappe.get_doc({
        "doctype": "Warehouse Task", "stock_allocation": first.name, "task_type": "Pick",
        "warehouse": first._warehouse, "product": first.product, "planned_quantity": total_qty, "stock_uom": stock_uom,
        "batch_no": first.batch_no, "serial_no": first.serial_no, "source_bin": first.storage_bin,
        "destination_bin": first._staging_bin, "source_hu": first.handling_unit,
        "stock_type_from": first.stock_type, "stock_type_to": first.stock_type,
        "movement_type": process_type.movement_type, "priority": priority or "Normal", "status": "Open",
        "sequence": sequence, "wave": wave,
        "idempotency_key": "WT:" + "-".join(a.name for a in allocations),
        "stock_allocations": [{"stock_allocation": a.name, "allocated_quantity": a.allocated_quantity} for a in allocations],
    })
    attach_task(task, batch_key, reference_doctype="Outbound Delivery", reference_name=first.outbound_delivery)
    task.insert(ignore_permissions=True)
    return task.name

OPEN_TASK_STATUSES = ("Open", "On Hold", "Available", "Assigned", "In Process", "Partially Confirmed")

def task_names_for_allocations(allocation_names):
    # Every Warehouse Task tied to a set of Stock Allocations, whether picked individually
    # (Warehouse Task.stock_allocation) or as part of a cluster pick (the Warehouse Task
    # Allocation child table) - shared by the RF picking-entry lookup, the Outbound Delivery
    # cancel cascade, and the Monitor's per-delivery execution status.
    if not allocation_names: return set()
    cluster_task_names = frappe.get_all("Warehouse Task Allocation", filters={"stock_allocation": ["in", allocation_names]}, pluck="parent")
    direct_task_names = frappe.get_all("Warehouse Task", filters={"stock_allocation": ["in", allocation_names]}, pluck="name")
    return set(cluster_task_names) | set(direct_task_names)

def my_resource(user=None):
    user = user or frappe.session.user
    return frappe.db.get_value("WMS Resource", {"user": user, "active": 1}, ["name", "warehouse", "current_queue"], as_dict=True)

def list_my_tasks(user=None):
    resource = my_resource(user)
    filters = {"status": ["in", OPEN_TASK_STATUSES], "docstatus": 0}
    if resource: filters["warehouse"] = resource.warehouse
    tasks = frappe.get_list(
        "Warehouse Task",
        filters=filters,
        fields=["name", "task_type", "warehouse", "product", "planned_quantity", "confirmed_quantity",
            "stock_uom", "source_bin", "destination_bin", "source_hu", "destination_hu",
            "priority", "status", "movement_type", "sequence", "queue", "wave", "warehouse_order", "assigned_resource",
            "blocking_reason"],
        order_by="priority desc, wave asc, sequence asc, creation asc",
        limit=200,
    )
    if resource:
        # Visible if it's mine, unrouted (no queue configured), or sitting unclaimed in my current queue.
        tasks = [t for t in tasks if t.assigned_resource == resource.name
            or (not t.assigned_resource and (not t.queue or t.queue == resource.current_queue))][:100]
    return {"resource": resource, "tasks": tasks}

def raise_exception(task_name, exception_code, remarks=None):
    require_role("WMS Operator", "WMS Supervisor")
    code = frappe.get_cached_doc("WMS Exception Code", exception_code)
    if not code.active: frappe.throw(_("Exception code {0} is not active").format(exception_code))
    if code.requires_supervisor: require_role("WMS Supervisor")
    if code.requires_comment and not (remarks or "").strip(): frappe.throw(_("This exception requires a comment"))
    frappe.db.sql("select name from `tabWarehouse Task` where name=%s for update", task_name)
    task = frappe.get_doc("Warehouse Task", task_name)
    if task.docstatus == 1: frappe.throw(_("Task is already confirmed"))
    task.db_set({"status": "Exception", "exception_code": exception_code, "blocking_reason": remarks}, update_modified=True)
    sync_warehouse_order(task.warehouse_order)
    return {"task": task.name, "status": "Exception"}

def confirm_task(task_name, scanned_source=None, scanned_destination=None, confirmed_quantity=None, destination_hu=None, device=None, idempotency_key=None):
    require_role("WMS Operator", "WMS Supervisor")
    frappe.db.sql("select name from `tabWarehouse Task` where name=%s for update", task_name)
    task = frappe.get_doc("Warehouse Task", task_name)
    if task.status == "Confirmed": return {"task": task.name, "status": task.status, "already_confirmed": True}
    if task.docstatus == 2 or task.status in {"Cancelled", "Exception"}: frappe.throw(_("Task is not confirmable"))
    if task.status == "On Hold": frappe.throw(task.blocking_reason or _("Task is on hold behind an earlier task in its Warehouse Order"))
    if scanned_source and scanned_source not in {task.source_bin, task.source_hu}: frappe.throw(_("Scanned source does not match the task"))
    if scanned_destination and scanned_destination not in {task.destination_bin, task.destination_hu}: frappe.throw(_("Scanned destination does not match the task"))
    already_confirmed = flt(task.confirmed_quantity)
    qty = flt(confirmed_quantity) if confirmed_quantity is not None else flt(task.planned_quantity) - already_confirmed
    new_confirmed = already_confirmed + qty
    if qty <= 0 or round(new_confirmed, 6) > round(flt(task.planned_quantity), 6): frappe.throw(_("Invalid confirmed quantity"))
    resolved_destination_hu = destination_hu or task.destination_hu or task.source_hu
    source = {"warehouse": task.warehouse, "product": task.product, "batch_no": task.batch_no, "serial_no": task.serial_no, "handling_unit": task.source_hu, "storage_bin": task.source_bin, "stock_type": task.stock_type_from, "stock_uom": task.stock_uom}
    destination = {"handling_unit": resolved_destination_hu, "storage_bin": task.destination_bin, "stock_type": task.stock_type_to or task.stock_type_from}
    key = idempotency_key or f"{task.idempotency_key or task.name}:{already_confirmed}"
    transfer_stock(source=source, destination=destination, quantity=qty, movement_type=task.movement_type, reference_doctype=task.doctype, reference_name=task.name, idempotency_key=key, warehouse_task=task.name, device=device)
    fully_confirmed = round(new_confirmed, 6) >= round(flt(task.planned_quantity), 6)
    status = "Confirmed" if fully_confirmed else "Partially Confirmed"
    updates = {"confirmed_quantity": new_confirmed, "status": status, "confirmed_at": now_datetime(), "confirmed_by": frappe.session.user, "confirmation_device": device, "idempotency_key": key, "destination_hu": resolved_destination_hu}
    if fully_confirmed: updates["docstatus"] = 1
    task.db_set(updates, update_modified=True)
    _update_request(task.warehouse_request)
    _update_allocations(task, qty)
    if fully_confirmed: _move_hu_if_complete(task, destination_hu)
    if fully_confirmed and task.task_type == "Putaway":
        create_print_spool("Warehouse Task", task.name, "Putaway Confirmed", task.warehouse)
    sync_warehouse_order(task.warehouse_order)
    released_tasks = release_next_in_sequence(task.warehouse_order) if fully_confirmed else []
    return {"task": task.name, "status": status, "quantity": qty, "released_tasks": released_tasks}

def _update_allocations(task, qty):
    rows = task.get("stock_allocations") or ([frappe._dict(stock_allocation=task.stock_allocation, allocated_quantity=qty)] if task.stock_allocation else [])
    if not rows: return
    release_allocation({"warehouse": task.warehouse, "product": task.product, "batch_no": task.batch_no, "serial_no": task.serial_no, "handling_unit": task.source_hu, "storage_bin": task.source_bin, "stock_type": task.stock_type_from}, qty)
    remaining = qty
    for row in rows:
        if remaining <= 0: break
        allocation = frappe.get_doc("Stock Allocation", row.stock_allocation)
        outstanding = flt(allocation.allocated_quantity) - flt(allocation.picked_quantity)
        if outstanding <= 0: continue
        take = min(remaining, outstanding)
        picked = flt(allocation.picked_quantity) + take
        status = "Picked" if picked >= flt(allocation.allocated_quantity) else "Partially Picked"
        frappe.db.set_value("Stock Allocation", allocation.name, {"picked_quantity": picked, "status": status})
        if row.get("name"):
            frappe.db.set_value("Warehouse Task Allocation", row.name, "picked_quantity", flt(row.picked_quantity) + take)
        if allocation.outbound_delivery_item:
            current = flt(frappe.db.get_value("Outbound Delivery Item", allocation.outbound_delivery_item, "picked_quantity"))
            frappe.db.set_value("Outbound Delivery Item", allocation.outbound_delivery_item, "picked_quantity", current + take)
        _update_delivery_picking_status(allocation.outbound_delivery)
        remaining -= take

def _update_delivery_picking_status(delivery_name):
    if not delivery_name: return
    rows = frappe.get_all("Outbound Delivery Item", filters={"parent": delivery_name}, fields=["requested_quantity", "picked_quantity"])
    if not rows: return
    fully_picked = all(flt(r.picked_quantity) >= flt(r.requested_quantity) for r in rows)
    any_picked = any(flt(r.picked_quantity) > 0 for r in rows)
    picking_status = "Picked" if fully_picked else ("Partially Picked" if any_picked else "Not Started")
    values = {"picking_status": picking_status}
    if fully_picked: values["status"] = "Picked"
    frappe.db.set_value("Outbound Delivery", delivery_name, values)

def _update_request(name):
    if not name: return
    totals = frappe.db.sql("select coalesce(sum(planned_quantity),0), coalesce(sum(confirmed_quantity),0), count(*), sum(status='Confirmed') from `tabWarehouse Task` where warehouse_request=%s and docstatus<2", name)[0]
    status = "Completed" if totals[2] and totals[2] == totals[3] else "In Process"
    frappe.db.set_value("Warehouse Request", name, {"created_quantity": totals[0], "confirmed_quantity": totals[1], "status": status})

def _move_hu_if_complete(task, destination_hu=None):
    hu = destination_hu or task.destination_hu or task.source_hu
    if not hu or not task.destination_bin: return
    if task.move_top_hu:
        hu = frappe.db.get_value("Handling Unit", hu, "top_hu") or hu
    _move_hu_and_descendants(hu, task.destination_bin, task.source_bin, task, top_level=True)

def _move_hu_and_descendants(hu, destination_bin, source_bin, task, top_level):
    doc = frappe.get_doc("Handling Unit", hu)
    if doc.current_bin == destination_bin: return
    bin_before = doc.current_bin
    doc.flags.wms_service_update = True
    doc.current_bin = destination_bin
    if top_level: doc.status = "Staged" if task.task_type in ("Stage", "Pick") else doc.status
    doc.save(ignore_permissions=True)
    frappe.get_doc({"doctype": "Handling Unit Event", "handling_unit": hu, "event_type": "Moved", "bin_before": bin_before or source_bin, "bin_after": destination_bin, "warehouse_task": task.name, "event_timestamp": now_datetime(), "performed_by": frappe.session.user}).insert(ignore_permissions=True)
    for child in frappe.get_all("Handling Unit", filters={"parent_hu": hu}, pluck="name"):
        _move_hu_and_descendants(child, destination_bin, source_bin, task, top_level=False)

def reverse_task(task_name, reason=None):
    # Creates and confirms a compensating task that moves the confirmed quantity back from
    # destination to source, rather than un-confirming the original (the stock ledger is
    # immutable, mirroring how goods receipt/issue reversals work). This corrects the physical
    # stock position; it does not cascade into the Stock Allocation/Outbound Delivery status
    # that a Pick task's confirmation may have advanced.
    require_role("WMS Supervisor")
    frappe.db.sql("select name from `tabWarehouse Task` where name=%s for update", task_name)
    original = frappe.get_doc("Warehouse Task", task_name)
    if original.docstatus != 1 or original.status != "Confirmed":
        frappe.throw(_("Only a fully confirmed task can be reversed"))
    if frappe.db.exists("Warehouse Task", {"reversal_of": original.name}):
        frappe.throw(_("Task has already been reversed"))
    qty = flt(original.confirmed_quantity)
    reversal = frappe.get_doc({
        "doctype": "Warehouse Task", "task_type": original.task_type, "warehouse": original.warehouse,
        "product": original.product, "planned_quantity": qty, "stock_uom": original.stock_uom,
        "batch_no": original.batch_no, "serial_no": original.serial_no,
        "source_bin": original.destination_bin, "destination_bin": original.source_bin,
        "source_hu": original.destination_hu or original.source_hu, "destination_hu": original.source_hu,
        "stock_type_from": original.stock_type_to or original.stock_type_from, "stock_type_to": original.stock_type_from,
        "movement_type": original.movement_type, "priority": original.priority, "status": "Open",
        "reversal_of": original.name, "idempotency_key": f"{original.idempotency_key or original.name}:reversal",
    })
    reversal.insert(ignore_permissions=True)
    result = confirm_task(reversal.name, confirmed_quantity=qty)
    frappe.db.set_value("Warehouse Task", original.name, "blocking_reason", reason or _("Reversed by {0}").format(reversal.name))
    return {"original": original.name, "reversal": reversal.name, "status": result["status"]}
